[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
presale = "6En2g3XUQgZSBEgBE1DF1sVeRik4KNvug151Zswz8oR5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/presale.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
